# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09df7a2aa906c50c2a4490004b8fce3c63bf49f9f340f356ed00acd2b7a7fdd8e3ae90004763da777d6a0bce26969867dfe798ca293271a5f1557541789e911d

test:
  secret_key_base: 2a3284159a838d7abfb4c32d060c6b3164c7a09a0f2672d586756b2aa9050c82949c2e8839600562ccacafee5fa384f70adbc5d994c1f659b0b9de25a3fbd372

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
